# action.yml
name: 'Code Review with ChatGPT'
description: 'Automating code review using ChatGPT with Github Actions integration on PRs for code explanations.'
inputs:
  openai_api_key:  # id of input
    description: 'OpenAI API Key'
    required: true
    default: ''
  github_token:  # id of input
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id:  # id of input
    description: 'Github PR ID'
    required: true
    default: ''
  openai_engine:  # id of input
    description: 'GPT models to be used.'
    required: false
    default: 'gpt-3.5-turbo'
  openai_temperature:  # id of input
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.'
    required: false
    default: '0.5'
  openai_max_tokens:  # id of input
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '2048'
  file_filter:  # id of input
    description: 'Filters which file format to be reviewed.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
    - ${{ inputs.openai_engine }}
    - ${{ inputs.openai_temperature }}
    - ${{ inputs.openai_max_tokens }}
    - ${{ inputs.file_filter }}
